//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18449.
// 
#pragma warning disable 1591

namespace ConsoleApp2.Submit {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubmitSoap", Namespace="http://tempuri.org/")]
    public partial class Submit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitSampleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetuserinfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSampleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMD5ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserGUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetfiletypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadAllReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadSampleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Submit() {
            this.Url = global::ConsoleApp2.Properties.Settings.Default.CodeTest_Submit_Submit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitSampleCompletedEventHandler SubmitSampleCompleted;
        
        /// <remarks/>
        public event GetuserinfoCompletedEventHandler GetuserinfoCompleted;
        
        /// <remarks/>
        public event GetSampleListCompletedEventHandler GetSampleListCompleted;
        
        /// <remarks/>
        public event GetMD5ListCompletedEventHandler GetMD5ListCompleted;
        
        /// <remarks/>
        public event AuthenticateUserCompletedEventHandler AuthenticateUserCompleted;
        
        /// <remarks/>
        public event GetUserGUIDCompletedEventHandler GetUserGUIDCompleted;
        
        /// <remarks/>
        public event GetfiletypeCompletedEventHandler GetfiletypeCompleted;
        
        /// <remarks/>
        public event DownloadAllReportCompletedEventHandler DownloadAllReportCompleted;
        
        /// <remarks/>
        public event DownloadSampleCompletedEventHandler DownloadSampleCompleted;
        
        /// <remarks/>
        public event DownloadReportCompletedEventHandler DownloadReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubmitSample(string file_name, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] file_content, System.Guid userId, string file_type) {
            object[] results = this.Invoke("SubmitSample", new object[] {
                        file_name,
                        file_content,
                        userId,
                        file_type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitSampleAsync(string file_name, byte[] file_content, System.Guid userId, string file_type) {
            this.SubmitSampleAsync(file_name, file_content, userId, file_type, null);
        }
        
        /// <remarks/>
        public void SubmitSampleAsync(string file_name, byte[] file_content, System.Guid userId, string file_type, object userState) {
            if ((this.SubmitSampleOperationCompleted == null)) {
                this.SubmitSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitSampleOperationCompleted);
            }
            this.InvokeAsync("SubmitSample", new object[] {
                        file_name,
                        file_content,
                        userId,
                        file_type}, this.SubmitSampleOperationCompleted, userState);
        }
        
        private void OnSubmitSampleOperationCompleted(object arg) {
            if ((this.SubmitSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitSampleCompleted(this, new SubmitSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getuserinfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Getuserinfo(string user, string comname, string ip, string country, string city, string time, string app, string upload, string download) {
            object[] results = this.Invoke("Getuserinfo", new object[] {
                        user,
                        comname,
                        ip,
                        country,
                        city,
                        time,
                        app,
                        upload,
                        download});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetuserinfoAsync(string user, string comname, string ip, string country, string city, string time, string app, string upload, string download) {
            this.GetuserinfoAsync(user, comname, ip, country, city, time, app, upload, download, null);
        }
        
        /// <remarks/>
        public void GetuserinfoAsync(string user, string comname, string ip, string country, string city, string time, string app, string upload, string download, object userState) {
            if ((this.GetuserinfoOperationCompleted == null)) {
                this.GetuserinfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetuserinfoOperationCompleted);
            }
            this.InvokeAsync("Getuserinfo", new object[] {
                        user,
                        comname,
                        ip,
                        country,
                        city,
                        time,
                        app,
                        upload,
                        download}, this.GetuserinfoOperationCompleted, userState);
        }
        
        private void OnGetuserinfoOperationCompleted(object arg) {
            if ((this.GetuserinfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetuserinfoCompleted(this, new GetuserinfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSampleList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetSampleList() {
            object[] results = this.Invoke("GetSampleList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSampleListAsync() {
            this.GetSampleListAsync(null);
        }
        
        /// <remarks/>
        public void GetSampleListAsync(object userState) {
            if ((this.GetSampleListOperationCompleted == null)) {
                this.GetSampleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSampleListOperationCompleted);
            }
            this.InvokeAsync("GetSampleList", new object[0], this.GetSampleListOperationCompleted, userState);
        }
        
        private void OnGetSampleListOperationCompleted(object arg) {
            if ((this.GetSampleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSampleListCompleted(this, new GetSampleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMD5List", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetMD5List() {
            object[] results = this.Invoke("GetMD5List", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMD5ListAsync() {
            this.GetMD5ListAsync(null);
        }
        
        /// <remarks/>
        public void GetMD5ListAsync(object userState) {
            if ((this.GetMD5ListOperationCompleted == null)) {
                this.GetMD5ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMD5ListOperationCompleted);
            }
            this.InvokeAsync("GetMD5List", new object[0], this.GetMD5ListOperationCompleted, userState);
        }
        
        private void OnGetMD5ListOperationCompleted(object arg) {
            if ((this.GetMD5ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMD5ListCompleted(this, new GetMD5ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AuthenticateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AuthenticateUser(string username, string password) {
            object[] results = this.Invoke("AuthenticateUser", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password) {
            this.AuthenticateUserAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateUserAsync(string username, string password, object userState) {
            if ((this.AuthenticateUserOperationCompleted == null)) {
                this.AuthenticateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserOperationCompleted);
            }
            this.InvokeAsync("AuthenticateUser", new object[] {
                        username,
                        password}, this.AuthenticateUserOperationCompleted, userState);
        }
        
        private void OnAuthenticateUserOperationCompleted(object arg) {
            if ((this.AuthenticateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserGUID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Guid GetUserGUID(string username) {
            object[] results = this.Invoke("GetUserGUID", new object[] {
                        username});
            return ((System.Guid)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserGUIDAsync(string username) {
            this.GetUserGUIDAsync(username, null);
        }
        
        /// <remarks/>
        public void GetUserGUIDAsync(string username, object userState) {
            if ((this.GetUserGUIDOperationCompleted == null)) {
                this.GetUserGUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserGUIDOperationCompleted);
            }
            this.InvokeAsync("GetUserGUID", new object[] {
                        username}, this.GetUserGUIDOperationCompleted, userState);
        }
        
        private void OnGetUserGUIDOperationCompleted(object arg) {
            if ((this.GetUserGUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserGUIDCompleted(this, new GetUserGUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Getfiletype", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Getfiletype() {
            object[] results = this.Invoke("Getfiletype", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetfiletypeAsync() {
            this.GetfiletypeAsync(null);
        }
        
        /// <remarks/>
        public void GetfiletypeAsync(object userState) {
            if ((this.GetfiletypeOperationCompleted == null)) {
                this.GetfiletypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetfiletypeOperationCompleted);
            }
            this.InvokeAsync("Getfiletype", new object[0], this.GetfiletypeOperationCompleted, userState);
        }
        
        private void OnGetfiletypeOperationCompleted(object arg) {
            if ((this.GetfiletypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetfiletypeCompleted(this, new GetfiletypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadAllReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadAllReport(string FName) {
            object[] results = this.Invoke("DownloadAllReport", new object[] {
                        FName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadAllReportAsync(string FName) {
            this.DownloadAllReportAsync(FName, null);
        }
        
        /// <remarks/>
        public void DownloadAllReportAsync(string FName, object userState) {
            if ((this.DownloadAllReportOperationCompleted == null)) {
                this.DownloadAllReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadAllReportOperationCompleted);
            }
            this.InvokeAsync("DownloadAllReport", new object[] {
                        FName}, this.DownloadAllReportOperationCompleted, userState);
        }
        
        private void OnDownloadAllReportOperationCompleted(object arg) {
            if ((this.DownloadAllReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadAllReportCompleted(this, new DownloadAllReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadSample(string FName, string filetype) {
            object[] results = this.Invoke("DownloadSample", new object[] {
                        FName,
                        filetype});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadSampleAsync(string FName, string filetype) {
            this.DownloadSampleAsync(FName, filetype, null);
        }
        
        /// <remarks/>
        public void DownloadSampleAsync(string FName, string filetype, object userState) {
            if ((this.DownloadSampleOperationCompleted == null)) {
                this.DownloadSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadSampleOperationCompleted);
            }
            this.InvokeAsync("DownloadSample", new object[] {
                        FName,
                        filetype}, this.DownloadSampleOperationCompleted, userState);
        }
        
        private void OnDownloadSampleOperationCompleted(object arg) {
            if ((this.DownloadSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadSampleCompleted(this, new DownloadSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadReport(string FName, string formatype) {
            object[] results = this.Invoke("DownloadReport", new object[] {
                        FName,
                        formatype});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void DownloadReportAsync(string FName, string formatype) {
            this.DownloadReportAsync(FName, formatype, null);
        }
        
        /// <remarks/>
        public void DownloadReportAsync(string FName, string formatype, object userState) {
            if ((this.DownloadReportOperationCompleted == null)) {
                this.DownloadReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadReportOperationCompleted);
            }
            this.InvokeAsync("DownloadReport", new object[] {
                        FName,
                        formatype}, this.DownloadReportOperationCompleted, userState);
        }
        
        private void OnDownloadReportOperationCompleted(object arg) {
            if ((this.DownloadReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadReportCompleted(this, new DownloadReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitSampleCompletedEventHandler(object sender, SubmitSampleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetuserinfoCompletedEventHandler(object sender, GetuserinfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetuserinfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetuserinfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSampleListCompletedEventHandler(object sender, GetSampleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSampleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSampleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMD5ListCompletedEventHandler(object sender, GetMD5ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMD5ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMD5ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void AuthenticateUserCompletedEventHandler(object sender, AuthenticateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserGUIDCompletedEventHandler(object sender, GetUserGUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserGUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserGUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Guid Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetfiletypeCompletedEventHandler(object sender, GetfiletypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetfiletypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetfiletypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownloadAllReportCompletedEventHandler(object sender, DownloadAllReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadAllReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadAllReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownloadSampleCompletedEventHandler(object sender, DownloadSampleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DownloadReportCompletedEventHandler(object sender, DownloadReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591